### ISSUE TITLE
create openapi documentation

### ISSUE THREAD

**Issue by allan-simon** [allan-simon/sentence-aligner-rust#1]
See if there's a crate to do this, or generate it manually

we can use openapi v3 as it's a brand new project

**Comment by jean553** [comment]
It seems there is no crate yet to handle that task automatically. There is this an ongoing project though: https://github.com/bluejekyll/rocket-openapi, but according to what I can see on Github threads, the project is not finished and not published as a crate either. I suggest to generate it manually for now?

**Comment by allan-simon** [comment]
manually ok

**Comment by jean553** [comment]
The full documentation is now available in `doc/openapi.json`.
