### ISSUE TITLE
separate language into a separate table

### ISSUE THREAD

**Issue by allan-simon** [allan-simon/sentence-aligner-rust#10]
Currently the 3-letter language info is stored "as it" into the sentence table,  in term of form validation, getting the list of supported language etc.  it would make more sentence to have it in a separate table

**Comment by jean553** [comment]
So you mean one new table "language" with one primary key column and one language value column. The "sentence" table gets a foreign key constraint to the language table. Is it what you expect ?

**Comment by jean553** [comment]
Should we create it at the same place as the sentence table ?

**Comment by allan-simon** [comment]
yes for the table structure , with a constraint of length 3 on the varchar-ish column 

for the moment we can create it at the same place

**Comment by jean553** [comment]
This has been finalized here https://github.com/allan-simon/sentence-aligner-rust/commit/76dd64c1802bcae3ee8bfd6de4ed41831e43b766 and merged.
