### ISSUE TITLE
Add a check that the text inside the structure of sentence match it's raw text

### ISSUE THREAD

**Issue by allan-simon** [allan-simon/sentence-aligner-rust#26]
i.e  

```
text:   Hello
structure:  <sentence>Bonjour</sentence>
```

should not be possible

**Comment by allan-simon** [comment]
postgresql has some xml manipulation function so it's certainly feasible as a `CHECK` in table definition

**Comment by jean553** [comment]
So, we want that only every words of the "content" field are present into the "structure" field. No more no less. The rest of the "structure" content would be XML tags only. Is this exactly what we want ?

**Comment by allan-simon** [comment]
yes, if you strip all the xml tags,  you're left with exactly, no more no less, the text content of the sentence

**Comment by jean553** [comment]
got it

**Comment by jean553** [comment]
By the way, do you have any idea or suggestion to handle that in SQL/PostgreSQL ? I didn't find any simple way to do that in SQL, though we can still do it directly in Rust.

**Comment by allan-simon** [comment]
you're right, after checking more in depth the xml functions available in postgresql, it seems there's nothing like that built-in, so we would better do it directly in rust.

**Comment by jean553** [comment]
ok

**Comment by jean553** [comment]
Can we use an external library to decode the sent XML (in order to check that every sent word is actually allowed to be inserted): https://github.com/tafia/quick-xml ?

**Comment by allan-simon** [comment]
Yes you can for the 3rd party lib but I don't understand the "every sent word" at this step you don't need to have a concept of word, you just need to consider the sentence as a whole

**Comment by jean553** [comment]
Ok.

**Comment by jean553** [comment]
Done here https://github.com/allan-simon/sentence-aligner-rust/commit/31c38c1aef531c38bf7656ac9cb870da6a2ec48c.
