### ISSUE TITLE
API to edit the language of a sentence

### ISSUE THREAD

**Issue by allan-simon** [allan-simon/sentence-aligner-rust#3]
we should have an api to only change the language of a sentence

**Comment by jean553** [comment]
After quick check of the code, I guess what you expect is the creation of the endpoint `PUT /sentences/<sentence_uuid>/language/<language_code>` into the `one_sentence.rs` file, am I right ?

**Comment by jean553** [comment]
Done https://github.com/allan-simon/sentence-aligner-rust/commit/9d9afba4a7bcf73bb5997f6257c6def60c80f88c
