### ISSUE TITLE
When post a sentence, check that the structure and the content match together

### ISSUE THREAD

**Issue by jean553** [allan-simon/sentence-aligner-rust#37]
As we do for the PUT sentence structure.

**Comment by allan-simon** [comment]
except if structure is not precise in the post.

**Comment by jean553** [comment]
Yes.

**Comment by jean553** [comment]
Done here https://github.com/allan-simon/sentence-aligner-rust/commit/b0ea8b2a636de98258d9f04993bc09386942c0a9.
