### ISSUE TITLE
[bug]Post new sentence accepts unknown language

### ISSUE THREAD

**Issue by allan-simon** [allan-simon/sentence-aligner-rust#39]
currently you can post a sentence with a language not known by the system and it will accept the post

BUT  it will insert `NULL` in the language field, implicitly swallowing 3-letters code unknown to the server. it should fail with noise instead.

**Comment by allan-simon** [comment]
https://stackoverflow.com/questions/35495928/have-sql-query-fail-if-subquery-returns-null  this one could permit that without requiring to split it in two requests.

**Comment by jean553** [comment]
Fixed by https://github.com/allan-simon/sentence-aligner-rust/commit/aa5abbb9e8ef366afe03f3b55f7af7e1ea4808cc.
