### ISSUE TITLE
Simplify tests

### ISSUE THREAD

**Issue by allan-simon** [allan-simon/sentence-aligner-rust#52]
in order to have readable test that only show the "functional" part , without the "dirty details" it may be a good idea to create a DB client class which hold the db connection  so that you could do 

```
let db_client = new_db_client();
db_client.clear_database();

let uuid = db_client.create_sentence(lang, text);
```

instead of 

```
    let first_sentence_uuid = uuid::Uuid::new_v4();
    let first_sentence_text = "This is the first sentence content.";
    db::insert_sentence(
        &connection,
        &first_sentence_uuid,
        &first_sentence_text,
        &language,
    );
```

(i.e the uuid creation and connection parameter are dirty details)

**Comment by jean553** [comment]
Ok, so it means wrapping the `connection` parameter into a structure, and create an implementation for this structure with the function `create_sentence` for instance. Right ?

**Comment by allan-simon** [comment]
yes

**Comment by allan-simon** [comment]
or maybe a trait to the connection object

**Comment by jean553** [comment]
"a trait to the connection object"... ? Do you have an example ?

**Comment by allan-simon** [comment]
you create a trait "DBClient" and you say that this trait is implemted by connection

**Comment by allan-simon** [comment]
like you can create a trait "to_chinese"  and you can implement for uint32  and then do 

`12.to_chinese()`

**Comment by jean553** [comment]
Ok

**Comment by jean553** [comment]
Fixed by https://github.com/allan-simon/sentence-aligner-rust/pull/63.
